import kotlinx.datetime.LocalDate
import org.beijing.model.Meal
import org.beijing.model.Nutrition

val mealsWithoutPotato = listOf(
    Meal(
        name = "Grilled Chicken Salad",
        id = 30,
        minutes = 25,
        contributorId = 130,
        submitted = LocalDate(2024, 9, 15),
        tags = listOf("salad", "grilled", "chicken"),
        nutrition = Nutrition(350.0, 25.0, 12.0, 500.0, 5.0, 3.0, 30.0),
        nSteps = 4,
        steps = listOf("Grill chicken", "Chop vegetables", "Assemble salad", "Serve"),
        description = "A healthy and fresh grilled chicken salad.",
        ingredients = listOf("chicken breast", "lettuce", "tomato", "cucumber", "olive oil"),
        nIngredients = 5
    ),
    Meal(
        name = "Spaghetti Aglio e Olio",
        id = 31,
        minutes = 20,
        contributorId = 131,
        submitted = LocalDate(2024, 10, 5),
        tags = listOf("pasta", "italian", "garlic"),
        nutrition = Nutrition(400.0, 10.0, 15.0, 600.0, 8.0, 4.0, 50.0),
        nSteps = 4,
        steps = listOf("Boil spaghetti", "Sauté garlic in olive oil", "Toss pasta with garlic oil", "Serve"),
        description = "A simple yet flavorful pasta with garlic and olive oil.",
        ingredients = listOf("spaghetti", "garlic", "olive oil", "chili flakes", "parsley"),
        nIngredients = 5
    ),
    Meal(
        name = "Vegan Stir-Fry",
        id = 32,
        minutes = 30,
        contributorId = 132,
        submitted = LocalDate(2024, 10, 10),
        tags = listOf("vegan", "stir-fry", "vegetarian"),
        nutrition = Nutrition(250.0, 10.0, 10.0, 300.0, 12.0, 5.0, 40.0),
        nSteps = 5,
        steps = listOf("Chop vegetables", "Stir-fry veggies in oil", "Add tofu", "Season with soy sauce", "Serve"),
        description = "A colorful and healthy stir-fry with tofu and vegetables.",
        ingredients = listOf("tofu", "bell pepper", "broccoli", "soy sauce", "ginger"),
        nIngredients = 5
    ),
    Meal(
        name = "Fish Tacos",
        id = 33,
        minutes = 30,
        contributorId = 133,
        submitted = LocalDate(2024, 10, 20),
        tags = listOf("mexican", "seafood", "taco"),
        nutrition = Nutrition(400.0, 20.0, 15.0, 600.0, 12.0, 3.0, 50.0),
        nSteps = 5,
        steps = listOf("Grill fish", "Warm tortillas", "Assemble tacos with toppings", "Serve"),
        description = "Tasty fish tacos with fresh toppings.",
        ingredients = listOf("fish fillets", "tortillas", "cabbage", "lime", "salsa"),
        nIngredients = 5
    ),
    Meal(
        name = "Quinoa Salad",
        id = 34,
        minutes = 35,
        contributorId = 134,
        submitted = LocalDate(2024, 10, 25),
        tags = listOf("vegan", "salad", "healthy"),
        nutrition = Nutrition(300.0, 8.0, 12.0, 450.0, 10.0, 4.0, 40.0),
        nSteps = 4,
        steps = listOf("Cook quinoa", "Chop vegetables", "Mix quinoa with veggies", "Serve chilled"),
        description = "A light and nutritious quinoa salad.",
        ingredients = listOf("quinoa", "cucumber", "tomato", "olive oil", "lemon"),
        nIngredients = 5
    )
)

//15 meals 5 contains potato and the rest not
val mealsContainsPotato = listOf(
    Meal(
        name = "Grilled Chicken Salad",
        id = 30,
        minutes = 25,
        contributorId = 130,
        submitted = LocalDate(2024, 9, 15),
        tags = listOf("salad", "grilled", "chicken"),
        nutrition = Nutrition(350.0, 25.0, 12.0, 500.0, 5.0, 3.0, 30.0),
        nSteps = 4,
        steps = listOf("Grill chicken", "Chop vegetables", "Assemble salad", "Serve"),
        description = "A healthy and fresh grilled chicken salad.",
        ingredients = listOf("chicken breast", "lettuce", "tomato", "cucumber", "olive oil"),
        nIngredients = 5
    ),
    Meal(
        name = "Spaghetti Aglio e Olio",
        id = 31,
        minutes = 20,
        contributorId = 131,
        submitted = LocalDate(2024, 10, 5),
        tags = listOf("pasta", "italian", "garlic"),
        nutrition = Nutrition(400.0, 10.0, 15.0, 600.0, 8.0, 4.0, 50.0),
        nSteps = 4,
        steps = listOf("Boil spaghetti", "Sauté garlic in olive oil", "Toss pasta with garlic oil", "Serve"),
        description = "A simple yet flavorful pasta with garlic and olive oil.",
        ingredients = listOf("spaghetti", "garlic", "olive oil", "chili flakes", "parsley"),
        nIngredients = 5
    ),
    Meal(
        name = "Vegan Stir-Fry",
        id = 32,
        minutes = 30,
        contributorId = 132,
        submitted = LocalDate(2024, 10, 10),
        tags = listOf("vegan", "stir-fry", "vegetarian"),
        nutrition = Nutrition(250.0, 10.0, 10.0, 300.0, 12.0, 5.0, 40.0),
        nSteps = 5,
        steps = listOf("Chop vegetables", "Stir-fry veggies in oil", "Add tofu", "Season with soy sauce", "Serve"),
        description = "A colorful and healthy stir-fry with tofu and vegetables.",
        ingredients = listOf("tofu", "bell pepper", "broccoli", "soy sauce", "ginger"),
        nIngredients = 5
    ),
    Meal(
        name = "Fish Tacos",
        id = 33,
        minutes = 30,
        contributorId = 133,
        submitted = LocalDate(2024, 10, 20),
        tags = listOf("mexican", "seafood", "taco"),
        nutrition = Nutrition(400.0, 20.0, 15.0, 600.0, 12.0, 3.0, 50.0),
        nSteps = 5,
        steps = listOf("Grill fish", "Warm tortillas", "Assemble tacos with toppings", "Serve"),
        description = "Tasty fish tacos with fresh toppings.",
        ingredients = listOf("fish fillets", "tortillas", "cabbage", "lime", "salsa"),
        nIngredients = 5
    ),
    Meal(
        name = "Quinoa Salad",
        id = 34,
        minutes = 35,
        contributorId = 134,
        submitted = LocalDate(2024, 10, 25),
        tags = listOf("vegan", "salad", "healthy"),
        nutrition = Nutrition(300.0, 8.0, 12.0, 450.0, 10.0, 4.0, 40.0),
        nSteps = 4,
        steps = listOf("Cook quinoa", "Chop vegetables", "Mix quinoa with veggies", "Serve chilled"),
        description = "A light and nutritious quinoa salad.",
        ingredients = listOf("quinoa", "cucumber", "tomato", "olive oil", "lemon"),
        nIngredients = 5
    ),
    Meal(
        name = "Vegetable Curry",
        id = 6,
        minutes = 40,
        contributorId = 106,
        submitted = LocalDate(2023, 10, 1),
        tags = listOf("vegan", "indian", "spicy"),
        nutrition = Nutrition(400.0, 15.0, 10.0, 500.0, 10.0, 5.0, 60.0),
        nSteps = 5,
        steps = listOf("Chop vegetables", "Sauté spices", "Add veggies", "Simmer with coconut milk", "Serve"),
        description = "Aromatic and hearty curry.",
        ingredients = listOf("potato", "carrot", "coconut milk", "curry powder", "onion"),
        nIngredients = 5
    ),
    Meal(
        name = "Potato Salad",
        id = 21,
        minutes = 30,
        contributorId = 121,
        submitted = LocalDate(2024, 1, 5),
        tags = listOf("salad", "side", "potato"),
        nutrition = Nutrition(350.0, 8.0, 18.0, 700.0, 12.0, 5.0, 40.0),
        nSteps = 4,
        steps = listOf("Boil potatoes", "Chop potatoes", "Mix with dressing", "Serve chilled"),
        description = "A classic potato salad with a creamy dressing.",
        ingredients = listOf("potato", "mayonnaise", "mustard", "onion", "celery"),
        nIngredients = 5
    ),
    Meal(
        name = "Mashed Potatoes",
        id = 22,
        minutes = 20,
        contributorId = 122,
        submitted = LocalDate(2024, 2, 10),
        tags = listOf("side", "comfort food"),
        nutrition = Nutrition(200.0, 4.0, 12.0, 300.0, 8.0, 2.0, 30.0),
        nSteps = 3,
        steps = listOf("Boil potatoes", "Mash potatoes", "Add butter and milk"),
        description = "Creamy mashed potatoes.",
        ingredients = listOf("potato", "butter", "milk", "salt", "pepper"),
        nIngredients = 5
    ),
    Meal(
        name = "Potato Soup",
        id = 23,
        minutes = 45,
        contributorId = 123,
        submitted = LocalDate(2024, 3, 15),
        tags = listOf("soup", "comfort food"),
        nutrition = Nutrition(300.0, 8.0, 15.0, 500.0, 10.0, 3.0, 40.0),
        nSteps = 5,
        steps = listOf("Boil potatoes", "Sauté onions", "Add broth", "Simmer", "Blend and season"),
        description = "A creamy and hearty potato soup.",
        ingredients = listOf("potato", "onion", "vegetable broth", "cream", "garlic"),
        nIngredients = 5
    ),
    Meal(
        name = "Potato Gratin",
        id = 24,
        minutes = 60,
        contributorId = 124,
        submitted = LocalDate(2024, 4, 2),
        tags = listOf("baking", "side", "potato"),
        nutrition = Nutrition(500.0, 10.0, 25.0, 800.0, 18.0, 8.0, 60.0),
        nSteps = 5,
        steps = listOf("Slice potatoes", "Layer in dish", "Add cream and cheese", "Bake", "Serve"),
        description = "A rich and cheesy potato gratin.",
        ingredients = listOf("potato", "cheese", "cream", "garlic", "butter"),
        nIngredients = 5
    ),
    Meal(
        name = "Potato Wedges",
        id = 25,
        minutes = 30,
        contributorId = 125,
        submitted = LocalDate(2024, 5, 10),
        tags = listOf("snack", "side", "potato"),
        nutrition = Nutrition(350.0, 5.0, 20.0, 600.0, 10.0, 4.0, 40.0),
        nSteps = 4,
        steps = listOf("Cut potatoes", "Season with spices", "Bake", "Serve"),
        description = "Crispy baked potato wedges.",
        ingredients = listOf("potato", "olive oil", "paprika", "garlic powder", "salt"),
        nIngredients = 5
    ),
    Meal(
        name = "Potato Tacos",
        id = 26,
        minutes = 25,
        contributorId = 126,
        submitted = LocalDate(2024, 6, 15),
        tags = listOf("mexican", "vegetarian", "taco"),
        nutrition = Nutrition(400.0, 10.0, 18.0, 600.0, 12.0, 5.0, 50.0),
        nSteps = 4,
        steps = listOf("Cook potatoes", "Warm tortillas", "Assemble tacos", "Serve"),
        description = "Tasty and filling vegetarian tacos.",
        ingredients = listOf("potato", "tortillas", "cheese", "lettuce", "salsa"),
        nIngredients = 5
    ),
    Meal(
        name = "Potato and Egg Breakfast Burrito",
        id = 27,
        minutes = 20,
        contributorId = 127,
        submitted = LocalDate(2024, 7, 5),
        tags = listOf("breakfast", "quick", "potato"),
        nutrition = Nutrition(400.0, 15.0, 12.0, 500.0, 10.0, 3.0, 45.0),
        nSteps = 4,
        steps = listOf("Cook potatoes", "Scramble eggs", "Wrap in tortilla", "Serve"),
        description = "A hearty breakfast burrito with potatoes and eggs.",
        ingredients = listOf("potato", "egg", "tortilla", "cheese", "salsa"),
        nIngredients = 5
    ),
    Meal(
        name = "Shepherd's Pie",
        id = 28,
        minutes = 75,
        contributorId = 128,
        submitted = LocalDate(2024, 8, 10),
        tags = listOf("dinner", "comfort food", "potato"),
        nutrition = Nutrition(500.0, 20.0, 15.0, 700.0, 20.0, 10.0, 50.0),
        nSteps = 6,
        steps = listOf("Cook beef", "Prepare mashed potatoes", "Layer beef and potatoes", "Bake", "Serve"),
        description = "A comforting dish with mashed potatoes and savory beef.",
        ingredients = listOf("potato", "ground beef", "peas", "carrot", "onion"),
        nIngredients = 5
    ),
    Meal(
        name = "Potato Frittata",
        id = 29,
        minutes = 30,
        contributorId = 129,
        submitted = LocalDate(2024, 9, 20),
        tags = listOf("breakfast", "vegetarian", "egg"),
        nutrition = Nutrition(350.0, 12.0, 18.0, 400.0, 15.0, 6.0, 40.0),
        nSteps = 5,
        steps = listOf("Cook potatoes", "Beat eggs", "Mix eggs and potatoes", "Cook in pan", "Serve"),
        description = "A delicious frittata made with potatoes and eggs.",
        ingredients = listOf("potato", "egg", "onion", "cheese", "olive oil"),
        nIngredients = 5
    )
)

val nineMealsContainsPotato = listOf(
    Meal(
        name = "Grilled Chicken Salad",
        id = 30,
        minutes = 25,
        contributorId = 130,
        submitted = LocalDate(2024, 9, 15),
        tags = listOf("salad", "grilled", "chicken"),
        nutrition = Nutrition(350.0, 25.0, 12.0, 500.0, 5.0, 3.0, 30.0),
        nSteps = 4,
        steps = listOf("Grill chicken", "Chop vegetables", "Assemble salad", "Serve"),
        description = "A healthy and fresh grilled chicken salad.",
        ingredients = listOf("chicken breast", "lettuce", "tomato", "cucumber", "olive oil"),
        nIngredients = 5
    ),
    Meal(
        name = "Spaghetti Aglio e Olio",
        id = 31,
        minutes = 20,
        contributorId = 131,
        submitted = LocalDate(2024, 10, 5),
        tags = listOf("pasta", "italian", "garlic"),
        nutrition = Nutrition(400.0, 10.0, 15.0, 600.0, 8.0, 4.0, 50.0),
        nSteps = 4,
        steps = listOf("Boil spaghetti", "Sauté garlic in olive oil", "Toss pasta with garlic oil", "Serve"),
        description = "A simple yet flavorful pasta with garlic and olive oil.",
        ingredients = listOf("spaghetti", "garlic", "olive oil", "chili flakes", "parsley"),
        nIngredients = 5
    ),
    Meal(
        name = "Vegan Stir-Fry",
        id = 32,
        minutes = 30,
        contributorId = 132,
        submitted = LocalDate(2024, 10, 10),
        tags = listOf("vegan", "stir-fry", "vegetarian"),
        nutrition = Nutrition(250.0, 10.0, 10.0, 300.0, 12.0, 5.0, 40.0),
        nSteps = 5,
        steps = listOf("Chop vegetables", "Stir-fry veggies in oil", "Add tofu", "Season with soy sauce", "Serve"),
        description = "A colorful and healthy stir-fry with tofu and vegetables.",
        ingredients = listOf("tofu", "bell pepper", "broccoli", "soy sauce", "ginger"),
        nIngredients = 5
    ),
    Meal(
        name = "Fish Tacos",
        id = 33,
        minutes = 30,
        contributorId = 133,
        submitted = LocalDate(2024, 10, 20),
        tags = listOf("mexican", "seafood", "taco"),
        nutrition = Nutrition(400.0, 20.0, 15.0, 600.0, 12.0, 3.0, 50.0),
        nSteps = 5,
        steps = listOf("Grill fish", "Warm tortillas", "Assemble tacos with toppings", "Serve"),
        description = "Tasty fish tacos with fresh toppings.",
        ingredients = listOf("fish fillets", "tortillas", "cabbage", "lime", "salsa"),
        nIngredients = 5
    ),
    Meal(
        name = "Quinoa Salad",
        id = 34,
        minutes = 35,
        contributorId = 134,
        submitted = LocalDate(2024, 10, 25),
        tags = listOf("vegan", "salad", "healthy"),
        nutrition = Nutrition(300.0, 8.0, 12.0, 450.0, 10.0, 4.0, 40.0),
        nSteps = 4,
        steps = listOf("Cook quinoa", "Chop vegetables", "Mix quinoa with veggies", "Serve chilled"),
        description = "A light and nutritious quinoa salad.",
        ingredients = listOf("quinoa", "cucumber", "tomato", "olive oil", "lemon"),
        nIngredients = 5
    ),
    Meal(
        name = "Vegetable Curry",
        id = 6,
        minutes = 40,
        contributorId = 106,
        submitted = LocalDate(2023, 10, 1),
        tags = listOf("vegan", "indian", "spicy"),
        nutrition = Nutrition(400.0, 15.0, 10.0, 500.0, 10.0, 5.0, 60.0),
        nSteps = 5,
        steps = listOf("Chop vegetables", "Sauté spices", "Add veggies", "Simmer with coconut milk", "Serve"),
        description = "Aromatic and hearty curry.",
        ingredients = listOf("potato", "carrot", "coconut milk", "curry powder", "onion"),
        nIngredients = 5
    ),
    Meal(
        name = "Potato Salad",
        id = 21,
        minutes = 30,
        contributorId = 121,
        submitted = LocalDate(2024, 1, 5),
        tags = listOf("salad", "side", "potato"),
        nutrition = Nutrition(350.0, 8.0, 18.0, 700.0, 12.0, 5.0, 40.0),
        nSteps = 4,
        steps = listOf("Boil potatoes", "Chop potatoes", "Mix with dressing", "Serve chilled"),
        description = "A classic potato salad with a creamy dressing.",
        ingredients = listOf("potato", "mayonnaise", "mustard", "onion", "celery"),
        nIngredients = 5
    ),
    Meal(
        name = "Mashed Potatoes",
        id = 22,
        minutes = 20,
        contributorId = 122,
        submitted = LocalDate(2024, 2, 10),
        tags = listOf("side", "comfort food"),
        nutrition = Nutrition(200.0, 4.0, 12.0, 300.0, 8.0, 2.0, 30.0),
        nSteps = 3,
        steps = listOf("Boil potatoes", "Mash potatoes", "Add butter and milk"),
        description = "Creamy mashed potatoes.",
        ingredients = listOf("potato", "butter", "milk", "salt", "pepper"),
        nIngredients = 5
    ),
    Meal(
        name = "Potato Soup",
        id = 23,
        minutes = 45,
        contributorId = 123,
        submitted = LocalDate(2024, 3, 15),
        tags = listOf("soup", "comfort food"),
        nutrition = Nutrition(300.0, 8.0, 15.0, 500.0, 10.0, 3.0, 40.0),
        nSteps = 5,
        steps = listOf("Boil potatoes", "Sauté onions", "Add broth", "Simmer", "Blend and season"),
        description = "A creamy and hearty potato soup.",
        ingredients = listOf("potato", "onion", "vegetable broth", "cream", "garlic"),
        nIngredients = 5
    )
)